name: Upload Package to Repositories

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

# Section for pip
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine

    - name: Generate dist files
      run: python setup.py sdist

    - name: Upload to PIP
      shell: bash
      env:
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload -u ghfetch -p "$PYPI_PASSWORD" dist/*

# Section for apt
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6.1.0
      with:
        gpg_private_key: ${{ secrets.GPG_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Install dependencies
      run: sudo apt-get -y install python3 python3-pip python3-distutils-extra dh-python gpg debianutils devscripts debhelper

    - name: Build package
      shell: bash
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        cd debian
        sudo chmod +x rules
        debuild -S -p"gpg --batch --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback"

    - name: Upload package to apt
      run: |
        cp  debian/.dput.cf .
        sudo chmod +x *_source.changes
        dput -f ghfetch-ppa *_source.changes
